language: c
compiler: gcc


before_script:
        - sudo apt-get update -qq
        - sudo apt-get install -y libportaudio2 portaudio19-dev libasound2 libasound2-dev libyajl-dev libyajl1 yajl-tools cmake

install:
        - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
        - tar -xvf /tmp/cmocka-1.0.1.tar.xz
        - pushd cmocka-1.0.1 && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release .. && make && sudo make install && popd

script:
        - ./autogen.sh
        - ./configure && make

# Whitelists
branches:
        only:
                - master
                - develop
