env:
  global:
  - secure: OS6ncWVxSLjn9F/5zVVo9bMOOaVYPhDn8zRIp3g/VZNobrVbbRQr3Cgbzb1/b+VT6OKezknATIJvTkdRcNZQINLyHIWGoz0RGOVDCemD6PpwO5wk3SNkVj8/8x5ie84RGvZitRDO/4Vg4VHDw2ep8sIVSljWVsZO54Ycgl4kTKfYcso3BqEtKHfG01fjfn08r6HdY73jdXNyT2eUM/aLq3aSZtRbFfZWwIe84c5ZXoMW6fm1+Y7a0s3F7TZ0sGg3perakc2vGuWHYLtJLExmHwq71NdJ5rnCJ8tszmyWMambWAy0jKKVUri0coFwt8wR6QusuXPPRDtFl+SddxSNaQtRczOljk3cza+E4ina38sI1g3AEpa287e/osr24c3m5MxzMoFxYGcrPdKb0NBOp2r6X05Qe8b3Wg8tUpie08d69Z07AJQ2TMRuc+MuM5nUEtFAtOG4QeTJVomR6eoHGnV/qRRN+oAsVv6t67HP4KSAvOYPYXIm/zxq53sflzIcPH7QvyfQpzpfA60EiOT9R0NcprendpZxQYpSUfdeXav87tuXvs32vOoKnimlj9opfExg88A+Rz90kni78mzIRj8fliTqGDlf8cMiPnyj1tQL8vVghyCfJJtz3WVZxd2wHuaXHGt9VycoNrhh5v9i+Hq1VUrbZDk5xgQCswYsnzg=

sudo: true
language: c
compiler: gcc
addons:
  coverity_scan:
    project:
      name: earswideopen/ewo-core
    notification_email: matthieu@berjon.net
    build_command_prepend: "./autogen && ./configure && make clean"
    build_command: make -j 4
    branch_pattern: coverity_scan

before_script:
- "./.travis.sh"

script:
- "./autogen.sh"
- mkdir -p build && cd build
- "../configure"
- make

branches:
  only:
  - master
  - develop
  - coverity_scan
