sudo: true
language: c
compiler: gcc


before_script:
    - ./.travis.sh

script:
    - ./autogen.sh
    - mkdir -p build && cd build
    - ../configure
    - make

# Whitelists
branches:
    only:
        - master
        - develop
