# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
    - python: 3.6
    - python: 3.5
    - python: 2.7
    - python: 3.7
      dist: xenial
      env: TOXENV=flake8
    - python: 3.7
      dist: xenial
      env: TOXENV=docs
  allow_failures:
    - env: TOXENV=docs

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libportaudio2 portaudio19-dev libasound2 libasound2-dev

# command to install dependencies, e.g. pip install -r requirements.txt
# --use-mirrors
install: pip install --upgrade tox coveralls

# command to run tests, e.g. python setup.py test
script:  # If $TOXENV is not already set then set it py{27,35,36,37}
  export TOXENV=${TOXENV:-$(python3 -c "import sys; print('py{}{}'.format(*sys.version_info))")}
  tox -e ${TOXENV}

after_success:
  coveralls
